import { Language, ContentText } from './types';

export const TRANSLATIONS: Record<Language, ContentText> = {
  [Language.UZ]: {
    heroTitle: "O‘zbekistonning Yagona Raqamli Vaqt Infratuzilmasi",
    heroSubtitle: "Milliy qadriyatlar va kelajak texnologiyalari uyg‘unligi",
    ctaDemo: "Demo-ni ko‘ring",
    ctaExplore: "Platformani o‘rganing",
    features: "Funksiyalar",
    about: "Loyiha Haqida",
    calendar: "Tadbirlar Kalendari",
    map: "Xarita va Lokatsiya",
    analytics: "Analitika",
    contact: "Bog‘lanish",
    community: "Mahalla va Jamiyat",
    national: "Milliy Modullar",
    chatPlaceholder: "Milliy Kalendar haqida so‘rang...",
    chatWelcome: "Assalomu alaykum! Men Milliy Kalendar AI yordamchisiman. Qanday yordam bera olaman?",
    launchMap: "Xaritani Ishga Tushirish",
    loadingMap: "Tizimga ulanmoqda...",
    share: "Ulashish",
    copied: "Nusxalandi!",
    upcomingEvents: "Yaqinlashib kelayotgan tadbirlar",
    disclaimerTitle: "Diqqat: Loyiha Test Rejimida",
    disclaimerText: "Diqqat: Ushbu loyiha hozirda ishlab chiqilish bosqichida va faqat demo variant hisoblanadi. Haqiqiy xizmatlar hali ishga tushmagan.",
    founder: "Nurbek Valijonov",
    founderRole: "Asoschi va G'oya muallifi",
    readMore: "Batafsil",
    socialShare: "Ijtimoiy tarmoqlarda ulashish",
    filterType: "Turi bo'yicha",
    filterRegion: "Hudud bo'yicha",
    all: "Barchasi",
    viewEventsInRegion: "Hududdagi tadbirlar",
    getDirections: "Yo'nalish olish",
    close: "Yopish",
    initializing: "Tizim ishga tushmoqda...",
    loadingData: "Ma'lumotlar yuklanmoqda...",
    renderingMap: "Xarita chizilmoqda..."
  },
  [Language.EN]: {
    heroTitle: "Uzbekistan's Unified Digital Time Infrastructure",
    heroSubtitle: "The harmony of national values and future technologies",
    ctaDemo: "View Demo",
    ctaExplore: "Explore Platform",
    features: "Features",
    about: "About Project",
    calendar: "Event Calendar",
    map: "Map & Location",
    analytics: "Analytics",
    contact: "Contact",
    community: "Community & Mahalla",
    national: "National Modules",
    chatPlaceholder: "Ask about Milliy Kalendar...",
    chatWelcome: "Hello! I am the Milliy Kalendar AI assistant. How can I help you today?",
    launchMap: "Launch Live Map",
    loadingMap: "Establishing Uplink...",
    share: "Share",
    copied: "Copied!",
    upcomingEvents: "Upcoming Events",
    disclaimerTitle: "Attention: Project in Development",
    disclaimerText: "Notice: This project is currently under development. This website is a high-fidelity prototype created for demonstration purposes. We are finalizing features for the official launch.",
    founder: "Nurbek Valijonov",
    founderRole: "Founder & Creator",
    readMore: "Read More",
    socialShare: "Share on Social Media",
    filterType: "Filter by Type",
    filterRegion: "Filter by Region",
    all: "All",
    viewEventsInRegion: "View Events in Region",
    getDirections: "Get Directions",
    close: "Close",
    initializing: "Initializing System...",
    loadingData: "Loading Regional Data...",
    renderingMap: "Rendering 3D Terrain..."
  },
  [Language.RU]: {
    heroTitle: "Единственная Цифровая Временная Платформа Узбекистана",
    heroSubtitle: "Гармония национальных ценностей и технологий будущего",
    ctaDemo: "Просмотреть демо",
    ctaExplore: "Изучить платформу",
    features: "Функции",
    about: "О проекте",
    calendar: "Календарь событий",
    map: "Карта и локация",
    analytics: "Аналитика",
    contact: "Контакты",
    community: "Сообщество и Махалля",
    national: "Национальные модули",
    chatPlaceholder: "Спросите о Milliy Kalendar...",
    chatWelcome: "Здравствуйте! Я ИИ-ассистент Milliy Kalendar. Чем могу помочь?",
    launchMap: "Запустить карту",
    loadingMap: "Подключение...",
    share: "Поделиться",
    copied: "Скопировано!",
    upcomingEvents: "Предстоящие события",
    disclaimerTitle: "Внимание: Проект в разработке",
    disclaimerText: "Внимание: Этот проект находится в стадии разработки. Этот веб-сайт является высокоточным прототипом, созданным для демонстрационных целей.",
    founder: "Нурбек Валижонов",
    founderRole: "Основатель и автор идеи",
    readMore: "Подробнее",
    socialShare: "Поделиться в соцсетях",
    filterType: "По типу",
    filterRegion: "По региону",
    all: "Все",
    viewEventsInRegion: "События в регионе",
    getDirections: "Проложить маршрут",
    close: "Закрыть",
    initializing: "Инициализация...",
    loadingData: "Загрузка данных...",
    renderingMap: "Отрисовка карты..."
  }
};

export const MOCK_EVENTS = [
  { 
    id: 1, 
    title: 'Navruz Festival', 
    date: '2025-03-21', 
    time: '10:00 AM - 10:00 PM',
    type: 'Holiday', 
    region: 'Tashkent', 
    desc: 'National celebration of spring equinox featuring traditional food, music, and street performances.',
    organizer: 'Ministry of Culture'
  },
  { 
    id: 2, 
    title: 'Tech Summit 2025', 
    date: '2025-04-15', 
    time: '09:00 AM - 05:00 PM',
    type: 'Business', 
    region: 'Samarkand', 
    desc: 'Largest gathering of IT specialists in Central Asia discussing AI, Blockchain, and GovTech.',
    organizer: 'IT Park Uzbekistan'
  },
  { 
    id: 3, 
    title: 'Silk Road Art Fair', 
    date: '2025-05-10', 
    time: '11:00 AM - 08:00 PM',
    type: 'Culture', 
    region: 'Bukhara', 
    desc: 'Exhibition of traditional crafts, carpets, and modern art inspired by the Great Silk Road.',
    organizer: 'Hunarmand Association'
  },
  { 
    id: 4, 
    title: 'Gastronomy Week', 
    date: '2025-06-01', 
    time: '12:00 PM - 11:00 PM',
    type: 'Food', 
    region: 'Khiva', 
    desc: 'Culinary festival featuring regional dishes like Shivit Oshi and Tukhum Barak.',
    organizer: 'Tourism Committee'
  },
  { 
    id: 5, 
    title: 'Investment Forum', 
    date: '2025-06-20', 
    time: '08:30 AM - 06:00 PM',
    type: 'Business', 
    region: 'Tashkent', 
    desc: 'International investors meeting to discuss opportunities in Uzbekistan\'s growing economy.',
    organizer: 'MIFT'
  },
  { 
    id: 6, 
    title: 'Sharq Taronalari', 
    date: '2025-08-25', 
    time: '07:00 PM - 11:00 PM',
    type: 'Culture', 
    region: 'Samarkand', 
    desc: 'International music festival held in the Registan Square.',
    organizer: 'UNESCO & Uzbekistan Govt'
  },
];

export const ANALYTICS_DATA = [
  { name: 'Tashkent', events: 400, participation: 2400 },
  { name: 'Samarkand', events: 300, participation: 1398 },
  { name: 'Bukhara', events: 200, participation: 9800 },
  { name: 'Khiva', events: 278, participation: 3908 },
  { name: 'Fergana', events: 189, participation: 4800 },
];

export const DISCLAIMER_CONTENT = {
  UZ: "Diqqat: Ushbu loyiha hozirda ishlab chiqilish bosqichida va faqat demo variant hisoblanadi. Haqiqiy xizmatlar hali ishga tushmagan.",
  EN: "Notice: This project is currently under development. This website is a high-fidelity prototype created for demonstration purposes. We are finalizing features for the official launch."
};